sudo: required
language: r
cache: packages
cran: https://cloud.r-project.org
env:
  global:
    - CRAN_REPO=https://cloud.r-project.org
matrix:
  include:
  - os: linux
    dist: xenial
    services:
      - xvfb
    r: oldrel
    r_binary_packages:
      - BH
    addons:
      apt:
        sources:
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - libgdal-dev
          - libgeos-dev
          - libglpk-dev
          - libnlopt-dev
          - libproj-dev
          - libudunits2-dev
  - os: linux
    dist: xenial
    services:
      - xvfb
    r: release
    r_binary_packages:
      - BH
      - dplyr
      - stringi
      - RSQlite
      - igraph
    addons:
      apt:
        sources:
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - libgdal-dev
          - libgeos-dev
          - libglpk-dev
          - libnlopt-dev
          - libproj-dev
          - libudunits2-dev
    before_script:
      - Rscript -e 'install.packages("devtools", type = "source")'
    after_failure:
      - cat ./SpaDES.core.Rcheck/tests/test-all.Rout
    after_success:
      - travis_wait 15 Rscript -e 'covr::coveralls(type = "all", quiet = FALSE)'
      - Rscript -e 'lintr::lint_package()'
    r_github_packages:
      - jimhester/lintr
      - r-lib/covr
  - os: linux
    dist: xenial
    services:
      - xvfb
    r: devel
    r_binary_packages:
      - BH
      - dplyr
      - stringi
      - RSQlite
      - igraph
    addons:
      apt:
        sources:
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - libgdal-dev
          - libgeos-dev
          - libglpk-dev
          - libnlopt-dev
          - libproj-dev
          - libudunits2-dev
  - os: osx
    osx_image: xcode9.4
    addons:
      homebrew:
        packages:
        - glpk
        - libgit2
        - llvm
        update: true
    latex: false
    r_build_args: "--no-build-vignettes"
    r_check_args: "--as-cran --ignore-vignettes --no-examples"
    env:
      - GLPK=true
    before_install:
      - Rscript -e 'install.packages(c("digest", "igraph", "rgdal", "rgeos"), type = "source")'
  - os: osx
    osx_image: xcode9.4
    addons:
      homebrew:
        packages:
        - libgit2
        - llvm
        update: true
    latex: false
    r_build_args: "--no-build-vignettes"
    r_check_args: "--as-cran --ignore-vignettes --no-examples"
    env:
      - GLPK=false
    before_script:
      - Rscript -e 'install.packages(c("digest", "igraph", "rgdal", "rgeos"), type = "source")'
r_build_args: " "
r_check_args: "--as-cran"
warnings_are_errors: true
notifications:
  email:
    on_success: change
    on_failure: change
